-- MySQL Script generated by MySQL Workbench
-- 11/19/14 18:55:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema buap-comunication
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `buap-comunication` ;

-- -----------------------------------------------------
-- Schema buap-comunication
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `buap-comunication` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `buap-comunication` ;

-- -----------------------------------------------------
-- Table `buap-comunication`.`users_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`users_types` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`users_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`academic_administrative_units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`academic_administrative_units` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`academic_administrative_units` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`users` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `phone` VARCHAR(10) NULL,
  `extension_phone` VARCHAR(5) NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 2 COMMENT '0 Inactive\n1 Active\n2 Activation required',
  `remember_token` VARCHAR(100) NULL,
  `user_type_id` INT NOT NULL DEFAULT 1,
  `academic_administrative_unit_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_user_type1_idx` (`user_type_id` ASC),
  INDEX `fk_users_academic_administrative_unit1_idx` (`academic_administrative_unit_id` ASC),
  CONSTRAINT `fk_users_user_type1`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `buap-comunication`.`users_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_academic_administrative_unit1`
    FOREIGN KEY (`academic_administrative_unit_id`)
    REFERENCES `buap-comunication`.`academic_administrative_units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`events` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_dci` VARCHAR(6) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `start_day` DATE NOT NULL,
  `end_day` DATE NOT NULL,
  `place` VARCHAR(50) NOT NULL,
  `time` TIME NOT NULL,
  `has_cost` TINYINT(1) NOT NULL,
  `directed_to` ENUM('Público en general', 'Comunidad BUAP', 'Profesores', 'Estudiantes') NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '0 No Aprobado\n1 Pendiente\n2 En Proceso\n3 Aprobado',
  `description` TEXT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_events_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_events_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `buap-comunication`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`services` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `witness` VARCHAR(100) NULL,
  `observations` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`requests` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`requests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `request_number` INT NOT NULL,
  `post_number` INT NOT NULL,
  `date` DATE NOT NULL,
  `request` VARCHAR(100) NOT NULL,
  `academic_administrative_unit_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_requests_academic_administrative_units1_idx` (`academic_administrative_unit_id` ASC),
  INDEX `fk_requests_events1_idx` (`event_id` ASC),
  CONSTRAINT `fk_requests_academic_administrative_units1`
    FOREIGN KEY (`academic_administrative_unit_id`)
    REFERENCES `buap-comunication`.`academic_administrative_units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_requests_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `buap-comunication`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`printed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`printed` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`printed` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `material` VARCHAR(30) NOT NULL,
  `size` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`digital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`digital` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`digital` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `size` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`audio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`audio` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`audio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `length` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`tv`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`tv` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`tv` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `length` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`users_auth_operations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`users_auth_operations` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`users_auth_operations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(40) NOT NULL,
  `expiration` DATETIME NOT NULL,
  `type` TINYINT(1) NOT NULL COMMENT '1 Activate user\n2 Change password',
  `used` TINYINT(1) NOT NULL COMMENT '0 Not used\n1 Used',
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_auth_operations_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_auth_operations_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `buap-comunication`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`event_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`event_service` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`event_service` (
  `event_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  `start_service` DATE NOT NULL,
  `end_service` DATE NOT NULL,
  PRIMARY KEY (`event_id`, `service_id`),
  INDEX `fk_events_has_services_services1_idx` (`service_id` ASC),
  INDEX `fk_events_has_services_events1_idx` (`event_id` ASC),
  CONSTRAINT `fk_events_has_services_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `buap-comunication`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_has_services_services1`
    FOREIGN KEY (`service_id`)
    REFERENCES `buap-comunication`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `buap-comunication`.`users_types`
-- -----------------------------------------------------
START TRANSACTION;
USE `buap-comunication`;
INSERT INTO `buap-comunication`.`users_types` (`id`, `name`, `description`) VALUES (NULL, 'Cliente', 'Este usuario es de tipo cliente');
INSERT INTO `buap-comunication`.`users_types` (`id`, `name`, `description`) VALUES (NULL, 'Proveedor', 'Este usuario es de tipo proveedor');
INSERT INTO `buap-comunication`.`users_types` (`id`, `name`, `description`) VALUES (NULL, 'DCI', 'Este usuario es de tipo DCI');

COMMIT;


-- -----------------------------------------------------
-- Data for table `buap-comunication`.`academic_administrative_units`
-- -----------------------------------------------------
START TRANSACTION;
USE `buap-comunication`;
INSERT INTO `buap-comunication`.`academic_administrative_units` (`id`, `name`, `description`) VALUES (1, 'Facultad de Ciencias de la Computación', NULL);
INSERT INTO `buap-comunication`.`academic_administrative_units` (`id`, `name`, `description`) VALUES (2, 'Facultad de Administración', NULL);
INSERT INTO `buap-comunication`.`academic_administrative_units` (`id`, `name`, `description`) VALUES (3, 'Facultad de Arquitectura', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `buap-comunication`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `buap-comunication`;
INSERT INTO `buap-comunication`.`users` (`id`, `first_name`, `last_name`, `email`, `password`, `phone`, `extension_phone`, `status`, `remember_token`, `user_type_id`, `academic_administrative_unit_id`) VALUES (NULL, 'Javier ', 'Aguila', 'sjaca10@buap.mx', '$2a$10$hmOFJoVrG8XJCmLk34zIKe.pz4ndUNhfAlF.Jx5.P6R1L3jsyvRrG', NULL, NULL, 1, NULL, 1, 1);
INSERT INTO `buap-comunication`.`users` (`id`, `first_name`, `last_name`, `email`, `password`, `phone`, `extension_phone`, `status`, `remember_token`, `user_type_id`, `academic_administrative_unit_id`) VALUES (NULL, 'Israel', 'Cruz', 'jesus@buap.mx', '$2a$10$XjW2EHspJ6USdvHzB/mIDuEzPKYJ4vAYQOxCFPbot/3rXSc6GzGWq', NULL, NULL, 1, NULL, 1, 1);
INSERT INTO `buap-comunication`.`users` (`id`, `first_name`, `last_name`, `email`, `password`, `phone`, `extension_phone`, `status`, `remember_token`, `user_type_id`, `academic_administrative_unit_id`) VALUES (NULL, 'Ángelica ', 'Tenorio', 'angelica@buap.mx', '$2a$10$Y0GpbHflASQoa1oNmMle3OmnXU16ktkhiKxSV/PCbBKJb4NIb9l5K', NULL, NULL, 1, NULL, 1, 3);
INSERT INTO `buap-comunication`.`users` (`id`, `first_name`, `last_name`, `email`, `password`, `phone`, `extension_phone`, `status`, `remember_token`, `user_type_id`, `academic_administrative_unit_id`) VALUES (NULL, 'Jesús', 'Cruz', 'jesuslink00@gmail.com', '$2y$10$GFcVq7u..KHQkTzgM9x2qOIUFxX5S9eP/J5f27dcWFZCbaZUhanPO', NULL, NULL, 1, NULL, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `buap-comunication`.`events`
-- -----------------------------------------------------
START TRANSACTION;
USE `buap-comunication`;
INSERT INTO `buap-comunication`.`events` (`id`, `id_dci`, `name`, `start_day`, `end_day`, `place`, `time`, `has_cost`, `directed_to`, `status`, `description`, `user_id`) VALUES (1, '141110', '1er Torneo Sabatino de Ajedrez Blitz para no clasificados', '2014-11-15 ', '2014-11-15', 'Complejo Cultural Universitario', '08:00:00', 0, NULL, 0, '', 1);
INSERT INTO `buap-comunication`.`events` (`id`, `id_dci`, `name`, `start_day`, `end_day`, `place`, `time`, `has_cost`, `directed_to`, `status`, `description`, `user_id`) VALUES (2, '141108', 'Ballet Folklórico de México de Amalia Hernández', '2014-11-13 ', '2014-11-13', 'Complejo Cultural Universitario', '20:30:00', 100, NULL, 0, NULL, 2);
INSERT INTO `buap-comunication`.`events` (`id`, `id_dci`, `name`, `start_day`, `end_day`, `place`, `time`, `has_cost`, `directed_to`, `status`, `description`, `user_id`) VALUES (3, '141110', 'Los Ángeles Azules Sinfónico Regresa Al Complejo', '2014-11-15 ', '2014-11-15 ', 'Complejo Cultural Universitario', '17:00:00', 200, NULL, 1, NULL, 3);
INSERT INTO `buap-comunication`.`events` (`id`, `id_dci`, `name`, `start_day`, `end_day`, `place`, `time`, `has_cost`, `directed_to`, `status`, `description`, `user_id`) VALUES (4, '141108', 'México al Son de la Banda', '2014-11-13 ', '2014-11-13 ', 'Complejo Cultural Universitario', '11:00:00', 300, NULL, 1, NULL, 1);
INSERT INTO `buap-comunication`.`events` (`id`, `id_dci`, `name`, `start_day`, `end_day`, `place`, `time`, `has_cost`, `directed_to`, `status`, `description`, `user_id`) VALUES (5, '141108', 'México al Son de la Banda', '2014-11-13 ', '2014-11-13 ', 'Complejo Cultural Universitario', '17:00:00', 400, NULL, 2, NULL, 2);
INSERT INTO `buap-comunication`.`events` (`id`, `id_dci`, `name`, `start_day`, `end_day`, `place`, `time`, `has_cost`, `directed_to`, `status`, `description`, `user_id`) VALUES (6, '141110', 'México al Son de la Banda', '2014-11-15 ', '2014-11-15 ', 'Complejo Cultural Universitario', '12:00:00', 500, NULL, 2, NULL, 3);
INSERT INTO `buap-comunication`.`events` (`id`, `id_dci`, `name`, `start_day`, `end_day`, `place`, `time`, `has_cost`, `directed_to`, `status`, `description`, `user_id`) VALUES (7, '141110', 'Salsa El Taller', '2014-12-08', '2014-12-08', 'Complejo Cultural Universitario', '19:00:00', 600, NULL, 3, NULL, 1);
INSERT INTO `buap-comunication`.`events` (`id`, `id_dci`, `name`, `start_day`, `end_day`, `place`, `time`, `has_cost`, `directed_to`, `status`, `description`, `user_id`) VALUES (8, '141110', 'Salsa El Taller', '2014-12-09', '2014-12-09', 'Complejo Cultural Universitario', '19:00:00', 700, NULL, 3, NULL, 2);
INSERT INTO `buap-comunication`.`events` (`id`, `id_dci`, `name`, `start_day`, `end_day`, `place`, `time`, `has_cost`, `directed_to`, `status`, `description`, `user_id`) VALUES (9, '141110', 'Salsa El Taller', '2014-12-10', '2014-12-10', 'Complejo Cultural Universitario', '19:00:00', 800, NULL, 0, NULL, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `buap-comunication`.`services`
-- -----------------------------------------------------
START TRANSACTION;
USE `buap-comunication`;
INSERT INTO `buap-comunication`.`services` (`id`, `name`, `description`, `witness`, `observations`) VALUES (NULL, 'Radio', 'Difusión del evento a través de la radio.', NULL, NULL);
INSERT INTO `buap-comunication`.`services` (`id`, `name`, `description`, `witness`, `observations`) VALUES (NULL, 'TV', 'Difusión del evento a través de la televisión.', NULL, NULL);
INSERT INTO `buap-comunication`.`services` (`id`, `name`, `description`, `witness`, `observations`) VALUES (NULL, 'Web', 'Difusión del evento a través de la web.', NULL, NULL);
INSERT INTO `buap-comunication`.`services` (`id`, `name`, `description`, `witness`, `observations`) VALUES (NULL, 'Redes sociales', 'Difusión del evento a través de redes sociales.', NULL, NULL);
INSERT INTO `buap-comunication`.`services` (`id`, `name`, `description`, `witness`, `observations`) VALUES (NULL, 'Medios impresos', 'Difusión del evento a través de medios impresos.', NULL, NULL);

COMMIT;

