-- MySQL Script generated by MySQL Workbench
-- 11/06/14 10:54:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema buap-comunication
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `buap-comunication` ;

-- -----------------------------------------------------
-- Schema buap-comunication
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `buap-comunication` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `buap-comunication` ;

-- -----------------------------------------------------
-- Table `buap-comunication`.`users_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`users_types` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`users_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`academic_administrative_units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`academic_administrative_units` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`academic_administrative_units` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`users` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `position` VARCHAR(80) NULL,
  `cell_phone` VARCHAR(10) NULL,
  `buap_extension_phone` VARCHAR(5) NULL,
  `secondary_email` VARCHAR(50) NULL,
  `description` TEXT NULL,
  `user_type_id` INT NOT NULL,
  `academic_administrative_unit_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_user_type1_idx` (`user_type_id` ASC),
  INDEX `fk_users_academic_administrative_unit1_idx` (`academic_administrative_unit_id` ASC),
  CONSTRAINT `fk_users_user_type1`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `buap-comunication`.`users_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_academic_administrative_unit1`
    FOREIGN KEY (`academic_administrative_unit_id`)
    REFERENCES `buap-comunication`.`academic_administrative_units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`events` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`events` (
  `id` VARCHAR(6) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `start_day` DATE NOT NULL,
  `end_day` DATE NOT NULL,
  `place` VARCHAR(50) NOT NULL,
  `time` TIME NOT NULL,
  `head_name` VARCHAR(100) NOT NULL,
  `head_email` VARCHAR(50) NOT NULL,
  `head_phone` VARCHAR(10) NOT NULL,
  `status` ENUM('Pendiente', 'Aprobado', 'En Proceso', 'No Aprobado') NOT NULL,
  `observations` TEXT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_events_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_events_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `buap-comunication`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`targets_events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`targets_events` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`targets_events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`events_has_targets_events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`events_has_targets_events` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`events_has_targets_events` (
  `event_id` VARCHAR(6) NOT NULL,
  `target_event_id` INT NOT NULL,
  PRIMARY KEY (`event_id`, `target_event_id`),
  INDEX `fk_events_has_targets_events_targets_events1_idx` (`target_event_id` ASC),
  INDEX `fk_events_has_targets_events_events1_idx` (`event_id` ASC),
  CONSTRAINT `fk_events_has_targets_events_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `buap-comunication`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_has_targets_events_targets_events1`
    FOREIGN KEY (`target_event_id`)
    REFERENCES `buap-comunication`.`targets_events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`broadcast_channels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`broadcast_channels` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`broadcast_channels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '     ';


-- -----------------------------------------------------
-- Table `buap-comunication`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`services` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `broadcast_type` ENUM('Interna', 'Externa') NOT NULL,
  `observations` TEXT NULL,
  `broadcast_channel_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_services_broadcast_channels1_idx` (`broadcast_channel_id` ASC),
  CONSTRAINT `fk_services_broadcast_channels1`
    FOREIGN KEY (`broadcast_channel_id`)
    REFERENCES `buap-comunication`.`broadcast_channels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`media_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`media_plan` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`media_plan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `events_id` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_media_plan_events1_idx` (`events_id` ASC),
  CONSTRAINT `fk_media_plan_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `buap-comunication`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`media_plan_has_services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`media_plan_has_services` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`media_plan_has_services` (
  `media_plan_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  `duration` INT NOT NULL,
  PRIMARY KEY (`media_plan_id`, `service_id`),
  INDEX `fk_media_plan_has_services_services1_idx` (`service_id` ASC),
  INDEX `fk_media_plan_has_services_media_plan1_idx` (`media_plan_id` ASC),
  CONSTRAINT `fk_media_plan_has_services_media_plan1`
    FOREIGN KEY (`media_plan_id`)
    REFERENCES `buap-comunication`.`media_plan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_plan_has_services_services1`
    FOREIGN KEY (`service_id`)
    REFERENCES `buap-comunication`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`requests` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`requests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `request_number` INT NOT NULL,
  `post_number` INT NOT NULL,
  `request_line` ENUM('Oficio', 'Correo') NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `date` DATE NOT NULL,
  `service_start_day` DATE NOT NULL,
  `service_end_day` DATE NOT NULL,
  `request` VARCHAR(100) NOT NULL,
  `academic_administrative_unit_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_requests_academic_administrative_units1_idx` (`academic_administrative_unit_id` ASC),
  INDEX `fk_requests_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_requests_academic_administrative_units1`
    FOREIGN KEY (`academic_administrative_unit_id`)
    REFERENCES `buap-comunication`.`academic_administrative_units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_requests_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `buap-comunication`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`printed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`printed` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`printed` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `material` VARCHAR(30) NOT NULL,
  `size` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`digital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`digital` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`digital` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `size` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`audio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`audio` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`audio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `length` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buap-comunication`.`tv`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buap-comunication`.`tv` ;

CREATE TABLE IF NOT EXISTS `buap-comunication`.`tv` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `length` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `buap-comunication`.`users_types`
-- -----------------------------------------------------
START TRANSACTION;
USE `buap-comunication`;
INSERT INTO `buap-comunication`.`users_types` (`id`, `name`, `description`) VALUES (NULL, 'Cliente', 'Este usuario es de tipo cliente');
INSERT INTO `buap-comunication`.`users_types` (`id`, `name`, `description`) VALUES (NULL, 'Proveedor', 'Este usuario es de tipo proveedor');
INSERT INTO `buap-comunication`.`users_types` (`id`, `name`, `description`) VALUES (NULL, 'DCI', 'Este usuario es de tipo DCI');

COMMIT;


-- -----------------------------------------------------
-- Data for table `buap-comunication`.`targets_events`
-- -----------------------------------------------------
START TRANSACTION;
USE `buap-comunication`;
INSERT INTO `buap-comunication`.`targets_events` (`id`, `name`, `description`) VALUES (NULL, 'Estudiantes', 'Dirigido a estudiantes.');
INSERT INTO `buap-comunication`.`targets_events` (`id`, `name`, `description`) VALUES (NULL, 'Administrativos', 'Dirigido a administrativos.');
INSERT INTO `buap-comunication`.`targets_events` (`id`, `name`, `description`) VALUES (NULL, 'Acádemicos/Investigadores', 'Dirigido a acádemicos e investigadores.');
INSERT INTO `buap-comunication`.`targets_events` (`id`, `name`, `description`) VALUES (NULL, 'Público en General', 'Dirigido al público en general.');

COMMIT;


-- -----------------------------------------------------
-- Data for table `buap-comunication`.`broadcast_channels`
-- -----------------------------------------------------
START TRANSACTION;
USE `buap-comunication`;
INSERT INTO `buap-comunication`.`broadcast_channels` (`id`, `name`, `description`) VALUES (NULL, 'printed', 'Canal de difusión impresa.');
INSERT INTO `buap-comunication`.`broadcast_channels` (`id`, `name`, `description`) VALUES (NULL, 'digital', 'Canal de difusión digital.');
INSERT INTO `buap-comunication`.`broadcast_channels` (`id`, `name`, `description`) VALUES (NULL, 'audio', 'Canal de difusión de audio.');
INSERT INTO `buap-comunication`.`broadcast_channels` (`id`, `name`, `description`) VALUES (NULL, 'tv', 'Canal de difusión de TV.');

COMMIT;

